### ISSUE TITLE
Check if defensive bid is working

### ISSUE THREAD

**Issue by meesf** [meesf/RiskyGamesAndAgents#92] opened 2018-05-30 08:21 UTC
Jordi and i speculated about the defendive bid algorithm. Lets assume we are in th reinforcement phase and there are two territories A and B. Both are surrounded by two enemy territories with 5 enemy units each. The teritory values of A and B are the same, but A has 1 unit and B has 20 units. MARS has 5 reinforcements in total. Will MARS reinforce A or will he reinforce B (if the offensive bids are disregarded)? For both decisions is something to say.

**Comment by Uwila** [comment] 2018-06-04 09:27
Is this not duplicate of #91 ?

**Closed** 2018-06-11 08:15 UTC
